version: '3.5'

services:
  mongodb:
    image: mongo:4-bionic
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pwdmongo
    volumes:
      - mongo-data:/data/db
  
  mongo-express:
    image: mongo-express:0.54
    ports:
      - 8082:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pwdmongo
      - ME_CONFIG_MONGODB_SERVER=mongodb
      
volumes:
  mongo-data: